Repository prisma/prisma, pull requests merged in 2021-12, with the labels that each got.

#10507 fix(sdk): avoid unlinking QE library when running "prisma generate"
  packages/sdk/src/predefinedGeneratorResolvers.ts
Labels: topic: windows

#10645 fix(client): add stacktrace when rejectOnNotFound is enabled
  packages/client/src/__tests__/integration/happy/rejectNotFound/__snapshots__/test.ts.snap
  packages/client/src/__tests__/integration/happy/rejectNotFound/test.ts
  packages/client/src/runtime/utils/rejectOnNotFound.ts
Labels: team/client

#7668 fix(generator-helper): missing field types
  packages/generator-helper/src/dmmf.ts
Labels: kind/improvement, team/client
