Repository prisma/prisma, pull requests merged in 2023-12, with the labels that each got.

#21891 ci: Allow to use custom engine branch in client tests
  .github/actions/setup/action.yml
  .github/workflows/build-engine-branch.yml
  .github/workflows/test-template.yml
  .github/workflows/test.yml
  TESTING.md
  packages/cli/src/__tests__/commands/Studio.test.ts
  packages/cli/src/__tests__/commands/Version.test.ts
  packages/client/src/__tests__/integration/errors/corruption/test.ts
  packages/client/src/__tests__/integration/errors/missing-engine-native-binaryTarget/binary.test.ts
  packages/client/src/__tests__/integration/errors/missing-engine-native-binaryTarget/library.test.ts
  packages/client/src/__tests__/integration/errors/missing-engine/binary.test.ts
  packages/client/src/__tests__/integration/errors/missing-engine/library.test.ts
  packages/client/src/__tests__/integration/happy/binary/test.ts
  packages/client/src/__tests__/integration/happy/client-engine/test.ts
  packages/client/src/__tests__/integration/happy/custom-engine-binary/test.ts
  packages/client/src/__tests__/integration/happy/float-napi/dev.db
  packages/client/src/__tests__/integration/happy/middlewares-transaction/dev.db
  packages/client/src/__tests__/integration/happy/middlewares/dev.db
  packages/client/src/utils/generateInFolder.ts
  packages/fetch-engine/src/__tests__/download.test.ts
  packages/internals/src/__tests__/engine-commands/getEngineVersion.test.ts
  packages/internals/src/__tests__/getGenerators/getGenerators.test.ts
  packages/internals/src/__tests__/schemaEngineCommands.test.ts
Labels: topic: tech debt

#22312 fix(client): add polyfill for `performance` (global)
  helpers/compile/plugins/fill-plugin/fillPlugin.ts
  packages/client/helpers/build.ts
Labels: topic: driverAdapters - edge functions, topic: early access ⏱

#22237 ci: automatically update `@prisma/query-engine-wasm`
  .github/workflows/update-engines-version.yml
Labels: topic: early access ⏱

#21417 fix(client): make engine events type safe internally
  packages/client/src/runtime/RequestHandler.ts
  packages/client/src/runtime/core/engines/binary/BinaryEngine.ts
  packages/client/src/runtime/core/engines/common/Engine.ts
  packages/client/src/runtime/core/engines/common/types/Events.ts
  packages/client/src/runtime/core/engines/data-proxy/DataProxyEngine.ts
  packages/client/src/runtime/core/engines/data-proxy/utils/EngineTimestamp.test.ts
  packages/client/src/runtime/core/engines/data-proxy/utils/EngineTimestamp.ts
  packages/client/src/runtime/core/engines/index.ts
  packages/client/src/runtime/core/engines/library/LibraryEngine.ts
  packages/client/src/runtime/getPrismaClient.ts
  packages/client/tests/functional/logging-types/_matrix.ts
  packages/client/tests/functional/logging-types/prisma/_schema.ts
  packages/client/tests/functional/logging-types/tests.ts
Labels: tech/typescript, topic: tech debt

#21659 refactor: consistently use `binaryTarget` term
  packages/cli/helpers/run-tests.ts
  packages/cli/package.json
  packages/cli/src/Version.ts
  packages/cli/src/__tests__/commands/Version.test.ts
  packages/client/helpers/functional-test/run-tests.ts
  packages/client/src/__tests__/integration/errors/corruption/test.ts
  packages/client/src/__tests__/integration/errors/missing-engine-native-binaryTarget/binary.test.ts
  packages/client/src/__tests__/integration/errors/missing-engine-native-binaryTarget/library.test.ts
  packages/client/src/__tests__/integration/errors/missing-engine/binary.test.ts
  packages/client/src/__tests__/integration/errors/missing-engine/library.test.ts
  packages/client/src/__tests__/integration/happy/binary/test.ts
  packages/client/src/__tests__/integration/happy/chmod/test.ts
  packages/client/src/__tests__/integration/happy/custom-engine-binary/test.ts
  packages/client/src/generation/TSClient/TSClient.ts
  packages/client/src/generation/generateClient.ts
  packages/client/src/generation/utils/buildNFTAnnotations.ts
  packages/client/src/runtime/core/engines/binary/BinaryEngine.ts
  packages/client/src/runtime/core/engines/common/errors/engine-not-found/EngineNotFoundErrorInput.ts
  packages/client/src/runtime/core/engines/common/resolveEnginePath.ts
  packages/client/src/runtime/core/engines/common/types/ErrorWithLinkInput.ts
  packages/client/src/runtime/core/engines/common/utils/getErrorMessageWithLink.test.ts
  packages/client/src/runtime/core/engines/common/utils/getErrorMessageWithLink.ts
  packages/client/src/runtime/core/engines/library/LibraryEngine.ts
  packages/client/src/utils/ensureTestClientQueryEngine.ts
  packages/client/src/utils/generateInFolder.ts
  packages/client/src/utils/getTestClient.ts
  packages/engines/src/index.ts
  packages/engines/src/scripts/localinstall.ts
  packages/engines/src/scripts/postinstall.ts
  packages/fetch-engine/src/__tests__/download.test.ts
  packages/fetch-engine/src/download.ts
  packages/fetch-engine/src/utils.ts
  packages/get-platform/README.md
  packages/get-platform/bench/get-platform.bench.ts
  packages/get-platform/src/__tests__/getPlatform.test.ts
  packages/get-platform/src/binaryTargets.ts
  packages/get-platform/src/getNodeAPIName.ts
  packages/get-platform/src/getPlatform.ts
  packages/get-platform/src/index.ts
  packages/get-platform/src/test-utils/binaryTargetRegex.ts
  packages/get-platform/src/test-utils/jestSnapshotSerializer.js
  packages/internals/src/__tests__/getGenerators/getGenerators.test.ts
  packages/internals/src/engine-commands/getConfig.ts
  packages/internals/src/errorReporting.ts
  packages/internals/src/get-generators/getGenerators.ts
  packages/internals/src/get-generators/utils/fixBinaryTargets.ts
  packages/internals/src/get-generators/utils/getBinaryPathsByVersion.ts
  packages/internals/src/index.ts
  packages/internals/src/resolveBinary.ts
  packages/internals/src/sendPanic.ts
  packages/internals/src/utils/binaryTargetRegex.ts
  packages/internals/src/utils/getGitHubIssueUrl.ts
  pnpm-lock.yaml
Labels: tech/typescript, topic: tech debt
