Repository prisma/prisma, pull requests merged in 2023-11, with the labels that each got.

#21382 feat(client): wasm engine
  helpers/compile/plugins/copyFilePlugin.ts
  helpers/compile/plugins/fill-plugin/fillers/weakref.ts
  packages/cli/src/bin.ts
  packages/client/helpers/build.ts
  packages/client/package.json
  packages/client/src/generation/TSClient/TSClient.ts
  packages/client/src/generation/generateClient.ts
  packages/client/src/generation/utils/buildGetQueryEngineWasmModule.ts
  packages/client/src/runtime/core/engines/common/Engine.ts
  packages/client/src/runtime/core/engines/common/errors/engine-not-found/EngineNotFoundErrorInput.ts
  packages/client/src/runtime/core/engines/common/errors/engine-not-found/bundlerHasTamperedWithEngineCopy.ts
  packages/client/src/runtime/core/engines/common/errors/engine-not-found/howToFixEngineNotFoundNextjs.ts
  packages/client/src/runtime/core/engines/common/errors/engine-not-found/toolingHasTamperedWithEngineCopy.ts
  packages/client/src/runtime/core/engines/common/resolveEnginePath.ts
  packages/client/src/runtime/core/engines/library/DefaultLibraryLoader.ts
  packages/client/src/runtime/core/engines/library/LibraryEngine.test.ts
  packages/client/src/runtime/core/engines/library/LibraryEngine.ts
  packages/client/src/runtime/core/engines/library/WasmLibraryLoader.ts
  packages/client/src/runtime/core/engines/library/types/Library.ts
  packages/client/src/runtime/core/init/getEngineInstance.ts
  packages/client/src/runtime/core/init/resolveDatasourceUrl.ts
  packages/client/src/runtime/getPrismaClient.ts
  packages/client/src/utils/getTestClient.ts
  packages/client/tests/e2e/bundler-detection-error/tests/main.ts
  packages/client/tests/e2e/bundler-detection-error/tests/pnpm-lock.yaml
  packages/client/tests/e2e/nextjs-schema-not-found/_shared/test.ts
  packages/internals/src/client/getClientEngineType.ts
  pnpm-lock.yaml
Labels: topic: driverAdapters phase 2

#21274 test(client): port and improve more legacy tests
  packages/client/src/__tests__/integration/happy/distinct/.gitignore
  packages/client/src/__tests__/integration/happy/distinct/dev.db
  packages/client/src/__tests__/integration/happy/distinct/schema.prisma
  packages/client/src/__tests__/integration/happy/distinct/test.ts
  packages/client/tests/functional/distinct/_matrix.ts
  packages/client/tests/functional/distinct/prisma/_schema.ts
  packages/client/tests/functional/distinct/tests.ts
Labels: tech/typescript, topic: tech debt

#21989 test(metrics): avoid flaky test on `prisma_pool_connections_idle`
  packages/client/tests/functional/metrics/enabled/tests.ts
Labels: topic: tech debt

#21587 chore(tech-debt): specify minimum support Node.js version only once in preinstall.js
  packages/cli/scripts/preinstall.ts
  packages/cli/src/__tests__/preinstall.test.ts
Labels: tech/typescript, topic: node version, topic: tech debt

#22139 test(client): wasm engine
  .github/workflows/test-template.yml
  packages/client/package.json
  packages/client/src/runtime/core/engines/library/WasmLibraryLoader.ts
  packages/client/tests/functional/_example/tests.ts
  packages/client/tests/functional/_utils/defineMatrix.ts
  packages/client/tests/functional/_utils/getTestSuiteInfo.ts
  packages/client/tests/functional/_utils/getTestSuitePlan.ts
  packages/client/tests/functional/_utils/providers.ts
  packages/client/tests/functional/_utils/relationMode/conditionalError.ts
  packages/client/tests/functional/_utils/setupTestSuiteEnv.ts
  packages/client/tests/functional/_utils/types.ts
  packages/client/tests/functional/accelerate-metrics-check/tests.ts
  packages/client/tests/functional/binary-engine/restart/tests.ts
  packages/client/tests/functional/binary-engine/reuse-binary-engine/tests.ts
  packages/client/tests/functional/blog-update/tests.ts
  packages/client/tests/functional/datasource-overrides/tests.ts
  packages/client/tests/functional/driver-adapters/_utils/test-suite-options.ts
  packages/client/tests/functional/driver-adapters/adapter-nullability/tests.ts
  packages/client/tests/functional/engine-selection-logic/tests.ts
  packages/client/tests/functional/interactive-transactions/tests.ts
  packages/client/tests/functional/invalid-env-value/tests.ts
  packages/client/tests/functional/issues/15176/tests.ts
  packages/client/tests/functional/issues/21552-datetime-representation-compatibility/tests.ts
  packages/client/tests/functional/methods/findFirstOrThrow/tests.ts
  packages/client/tests/functional/metrics/enabled/tests.ts
  packages/client/tests/functional/middleware-raw-args/tests.ts
  packages/client/tests/functional/missing-env/tests.ts
  packages/client/tests/functional/order-by-null/tests.ts
  packages/client/tests/functional/query-validation/tests.ts
  packages/client/tests/functional/raw-queries/send-type-hints/tests.ts
  packages/client/tests/functional/raw-queries/typed-results/tests.ts
  packages/client/tests/functional/relationMode-17255-mixed-actions/tests.ts
  packages/client/tests/functional/relationMode-17255-same-actions/tests.ts
  packages/client/tests/functional/runtime-import/tests.ts
  packages/client/tests/functional/tracing/tests.ts
  pnpm-lock.yaml
Labels: topic: vertical slice 🍰, topic: driverAdapters - edge functions

#22168 test(driver-adapters): unskip undefined-vs-null tests
  packages/client/package.json
  packages/client/tests/functional/blog-update/tests.ts
  packages/client/tests/functional/relationMode-17255-mixed-actions/tests.ts
  packages/client/tests/functional/relationMode-17255-same-actions/tests.ts
  pnpm-lock.yaml
Labels: topic: driverAdapters - edge functions

#22172 test(client): unskip orderBy null tests for wasm
  packages/client/tests/functional/order-by-null/tests.ts
Labels: topic: vertical slice 🍰, topic: driverAdapters - edge functions
