Repository prisma/prisma, pull requests merged in 2024-04, with the labels that each got.

#23491 chore(d1): update README for Preview
  packages/adapter-d1/README.md
Labels: topic: @prisma/adapter-d1

#23971 fix(instrumentation): do not pin OTEL dependencies
  .github/renovate.json
  packages/instrumentation/package.json
  pnpm-lock.yaml
Labels: PR: Bug

#21195 feat(cli): Add a --with-model arg to generate an example schema
  packages/cli/src/Init.ts
  packages/cli/src/__tests__/commands/Init.test.ts
  packages/cli/src/__tests__/commands/__snapshots__/Init.test.ts.snap
Labels: PR: Feature
