Repository prisma/prisma, pull requests merged in 2024-03, with the labels that each got.

#22904 ci: use macOS 14
  .github/workflows/build-engine-branch.yml
  .github/workflows/test-template.yml
Labels: topic: tech debt

#23530 test(client): use `Providers` instead of strings
  TESTING.md
  packages/client/tests/functional/0-legacy-ports/aggregate-raw/tests.ts
  packages/client/tests/functional/0-legacy-ports/execute-raw/tests.ts
  packages/client/tests/functional/0-legacy-ports/find-raw/tests.ts
  packages/client/tests/functional/0-legacy-ports/malformed-id/tests.ts
  packages/client/tests/functional/0-legacy-ports/query-raw/tests.ts
  packages/client/tests/functional/0-legacy-ports/run-command-raw/tests.ts
  packages/client/tests/functional/21136-extensions-mocking-library/tests.ts
  packages/client/tests/functional/composites/list/_matrix.ts
  packages/client/tests/functional/composites/object/_matrix.ts
  packages/client/tests/functional/composites/recursive/tests.ts
  packages/client/tests/functional/composites/selection/tests.ts
  packages/client/tests/functional/decimal/scalar/tests.ts
  packages/client/tests/functional/driver-adapters/_utils/test-suite-options.ts
  packages/client/tests/functional/driver-adapters/binary-engine-error/_matrix.ts
  packages/client/tests/functional/driver-adapters/error-forwarding/_matrix.ts
  packages/client/tests/functional/driver-adapters/team-orm-687-bytes/_matrix.ts
  packages/client/tests/functional/issues/10000/tests.ts
  packages/client/tests/functional/issues/11233/tests.ts
  packages/client/tests/functional/issues/11974/tests.ts
  packages/client/tests/functional/issues/14271/tests.ts
  packages/client/tests/functional/issues/15177/tests.ts
  packages/client/tests/functional/issues/18276-batch-order/tests.ts
  packages/client/tests/functional/issues/20724/tests.ts
  packages/client/tests/functional/issues/21352-id-does-not-exist/tests.ts
  packages/client/tests/functional/issues/21369-select-null/tests.ts
  packages/client/tests/functional/issues/21592-char-truncation/_matrix.ts
  packages/client/tests/functional/issues/5952-decimal-batch/tests.ts
  packages/client/tests/functional/issues/6578/tests.ts
  packages/client/tests/functional/issues/9372/tests.ts
  packages/client/tests/functional/middleware-raw-args/tests.ts
  packages/client/tests/functional/order-by-null/tests.ts
  packages/client/tests/functional/raw-queries/mongo-sequential-tx/tests.ts
  packages/client/tests/functional/raw-queries/send-type-hints/tests.ts
  packages/client/tests/functional/raw-queries/typed-results/tests.ts
  packages/client/tests/functional/reconnect-failure/tests.ts
  packages/client/tests/functional/referentialActions-setDefault/tests_1-to-1.ts
  packages/client/tests/functional/referentialActions-setDefault/tests_1-to-n.ts
  packages/client/tests/functional/referentialIntegrity-property-deprecated/tests.ts
  packages/client/tests/functional/relationMode-17255-mixed-actions/tests.ts
  packages/client/tests/functional/relationMode-17255-same-actions/tests.ts
  packages/client/tests/functional/relationMode-in-separate-gh-action/tests_1-to-1.ts
  packages/client/tests/functional/relationMode-in-separate-gh-action/tests_1-to-n.ts
  packages/client/tests/functional/relationMode-in-separate-gh-action/tests_m-to-n-MongoDB.ts
  packages/client/tests/functional/relationMode-in-separate-gh-action/tests_m-to-n.ts
  packages/client/tests/functional/relationMode-m-n-mongodb-failing-with-at-map/tests_m-to-n-MongoDB.ts
  packages/client/tests/functional/type-declaration/tests.ts
  packages/client/tests/functional/unsupported-action/tests.ts
Labels: topic: tech debt

#23484 test(client): avoid flaky results for prisma_client_queries_wait
  packages/client/tests/functional/metrics/enabled/tests.ts
Labels: topic: tests

#17315 fix: change type `generator.config.output` to never as it is a dedicated field.
  packages/generator-helper/src/types.ts
Labels: PR: Improvement
