Repository prisma/prisma, pull requests merged in 2024-10, with the labels that each got.

#25483 fix(adapter-d1): throws Error when string column contains any ISO date
  packages/adapter-d1/src/conversion.ts
  packages/client/tests/functional/issues/25404/_matrix.ts
  packages/client/tests/functional/issues/25404/prisma/_schema.ts
  packages/client/tests/functional/issues/25404/test.ts
Labels: size:M, lgtm

#25535 fix(cli): `prisma version --json` suppress dotenv message
  packages/cli/src/Version.ts
Labels: size:XS, lgtm

#25457 feat(cli): [BREAKING] remove custom yarn logic
  .github/renovate.json
  packages/adapter-d1/src/conversion.ts
  packages/cli/src/Version.ts
  packages/cli/src/utils/checkpoint.ts
  packages/cli/src/utils/printUpdateMessage.ts
  packages/client/tests/functional/issues/25404/_matrix.ts
  packages/client/tests/functional/issues/25404/prisma/_schema.ts
  packages/client/tests/functional/issues/25404/test.ts
  packages/fetch-engine/src/utils.ts
  packages/internals/src/__tests__/__fixtures__/getSchema/conventional-path-workspaces/package.json
  packages/internals/src/__tests__/__fixtures__/getSchema/conventional-path-workspaces/packages/a/package.json
  packages/internals/src/__tests__/__fixtures__/getSchema/conventional-path-workspaces/packages/b/package.json
  packages/internals/src/__tests__/__fixtures__/getSchema/conventional-path-workspaces/packages/b/schema.prisma
  packages/internals/src/__tests__/__fixtures__/getSchema/no-schema-workspaces/package.json
  packages/internals/src/__tests__/__fixtures__/getSchema/pkg-json-workspace-parent/db/schema.prisma
  packages/internals/src/__tests__/__fixtures__/getSchema/pkg-json-workspace-parent/package.json
  packages/internals/src/__tests__/__fixtures__/getSchema/pkg-json-workspace-parent/packages/a/package.json
  packages/internals/src/__tests__/__fixtures__/getSchema/pkg-json-workspace-parent/packages/b/package.json
  packages/internals/src/__tests__/getSchema.test.ts
  packages/internals/src/cli/getSchema.ts
  packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/checkYarnVersion.ts
  packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts
  packages/internals/src/utils/getCommandWithExecutor.ts
  packages/internals/src/utils/isCurrentBinInstalledGlobally.ts
  packages/migrate/package.json
  packages/migrate/src/utils/seed.ts
  pnpm-lock.yaml
  scripts/check-version-conflicts.ts
Labels: size:L
