Repository prisma/prisma, pull requests merged in 2024-11, with the labels that each got.

#25497 chore(driver-adapters): bump `@neondatabase/serverless` peer dep version to ^0.10.0
  packages/adapter-neon/package.json
Labels: size:XS, lgtm

#25557 chore: Expose JsonQuery type in @prisma/client/runtime/library
  packages/client/src/runtime/index.ts
Labels: size:XS, lgtm

#25551 docs(README): add PPG to README
  README.md
Labels: size:S, lgtm

#25578 chore: fix linting failing on README.md
  README.md
Labels: size:XS, lgtm

#25576 chore: Expose serializeJsonQuery and deserializeJsonResponse
  packages/client/src/runtime/index.ts
Labels: size:XS, lgtm

#25585 chore: Small exports and changes for using Json Protocol types and utils in Studio
  packages/client/src/runtime/core/jsonProtocol/serializeJsonQuery.ts
  packages/client/src/runtime/index.ts
Labels: size:XS, lgtm

#25590 feat(cli): add new promo survey for Prisma 5.22
  packages/cli/src/Generate.ts
  packages/cli/src/__tests__/commands/Generate.test.ts
  packages/cli/src/utils/handlePromotions.ts
Labels: size:M, lgtm

#25588 test(client): accept 5.1.x as the minimum TypeScript version.
  packages/client/tests/e2e/ts-version/4.7/README.md
  packages/client/tests/e2e/ts-version/4.7/package.json
  packages/client/tests/e2e/ts-version/4.8/README.md
  packages/client/tests/e2e/ts-version/4.8/_steps.ts
  packages/client/tests/e2e/ts-version/4.8/prisma/schema.prisma
  packages/client/tests/e2e/ts-version/4.8/src/index.ts
  packages/client/tests/e2e/ts-version/4.8/tsconfig.json
  packages/client/tests/e2e/ts-version/4.9/README.md
  packages/client/tests/e2e/ts-version/4.9/_steps.ts
  packages/client/tests/e2e/ts-version/4.9/package.json
  packages/client/tests/e2e/ts-version/4.9/prisma/schema.prisma
  packages/client/tests/e2e/ts-version/4.9/src/index.ts
  packages/client/tests/e2e/ts-version/4.9/tsconfig.json
  packages/client/tests/e2e/ts-version/5.0/README.md
  packages/client/tests/e2e/ts-version/5.0/_steps.ts
  packages/client/tests/e2e/ts-version/5.0/package.json
  packages/client/tests/e2e/ts-version/5.0/prisma/schema.prisma
  packages/client/tests/e2e/ts-version/5.0/src/index.ts
  packages/client/tests/e2e/ts-version/5.0/tsconfig.json
  packages/client/tests/e2e/ts-version/5.6/README.md
  packages/client/tests/e2e/ts-version/5.6/_steps.ts
  packages/client/tests/e2e/ts-version/5.6/package.json
  packages/client/tests/e2e/ts-version/5.6/prisma/schema.prisma
  packages/client/tests/e2e/ts-version/5.6/src/index.ts
  packages/client/tests/e2e/ts-version/5.6/tsconfig.json
Labels: size:L, lgtm

#25635 chore(client)!: remove `NotFoundError`
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema-mongo/__snapshots__/binary.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema-mongo/__snapshots__/library.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema/__snapshots__/binary.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema/__snapshots__/library.test.ts.snap
  packages/client/src/generation/TSClient/common.ts
  packages/client/src/runtime/RequestHandler.ts
  packages/client/src/runtime/core/errors/NotFoundError.ts
  packages/client/src/runtime/core/model/applyModel.ts
  packages/client/src/runtime/core/model/applyOrThrowErrorAdapter.ts
  packages/client/src/runtime/index.ts
  packages/client/tests/e2e/browser-unsupported-errors/tests/main.ts
  packages/client/tests/functional/methods/findFirstOrThrow/tests.ts
  packages/client/tests/functional/methods/findUniqueOrThrow/tests.ts
  packages/client/tests/functional/query-error-logging/tests.ts
Labels: size:L, lgtm

#25651 fix(tests): don't run write conflicts stress test on mongodb
  packages/client/tests/functional/interactive-transactions/tests.ts
Labels: size:L, lgtm

#24610 feat: Add Made with Prisma badges to readme
  README.md
Labels: size:S

#24916 fix(migrate): correct types import path in @prisma/migrate
  packages/migrate/package.json
Labels: size:XS

#25703 feat(client): [breaking] remove type aliases introduced in #20184
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema-mongo/__snapshots__/binary.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema-mongo/__snapshots__/library.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema/__snapshots__/binary.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema/__snapshots__/library.test.ts.snap
  packages/client/src/generation/TSClient/Args.ts
  packages/client/src/generation/TSClient/DefaultArgsAliases.ts
  packages/client/src/generation/TSClient/GenerateContext.ts
  packages/client/src/generation/TSClient/Model.ts
  packages/client/src/generation/TSClient/TSClient.ts
  packages/client/src/generation/utils.ts
  packages/client/tests/functional/issues/20614-missing-legacy-aliases/_matrix.ts
  packages/client/tests/functional/issues/20614-missing-legacy-aliases/prisma/_schema.ts
  packages/client/tests/functional/issues/20614-missing-legacy-aliases/tests.ts
Labels: size:L, lgtm

#25719 feat(client)!: use `Uint8Array` for the `Bytes` type
  packages/client/src/__tests__/deserializeRawResults.test.ts
  packages/client/src/__tests__/integration/happy/mysql-binary-id/test.ts
  packages/client/src/__tests__/integration/happy/native-types-mysql/test.ts
  packages/client/src/__tests__/integration/happy/native-types-postgres/test.ts
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema-mongo/__snapshots__/binary.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema-mongo/__snapshots__/library.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema/__snapshots__/binary.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema/__snapshots__/library.test.ts.snap
  packages/client/src/__tests__/types/native-types/test.ts
  packages/client/src/generation/typedSql/mapTypes.ts
  packages/client/src/generation/utils/common.ts
  packages/client/src/runtime/core/jsonProtocol/deserializeJsonResponse.test.ts
  packages/client/src/runtime/core/jsonProtocol/deserializeJsonResponse.ts
  packages/client/src/runtime/core/jsonProtocol/serializeJsonQuery.test.ts
  packages/client/src/runtime/core/jsonProtocol/serializeJsonQuery.ts
  packages/client/src/runtime/utils/deserializeRawResults.ts
  packages/client/src/runtime/utils/serializeRawParameters.ts
  packages/client/tests/functional/driver-adapters/team-orm-687-bytes/tests.ts
  packages/client/tests/functional/multiple-types/tests.ts
  packages/client/tests/functional/raw-queries/send-type-hints/tests.ts
  packages/client/tests/functional/raw-queries/typed-results/tests.ts
  packages/client/tests/functional/typed-sql/mysql-scalars-nullable/test.ts
  packages/client/tests/functional/typed-sql/mysql-scalars/test.ts
  packages/client/tests/functional/typed-sql/postgres-lists/test.ts
  packages/client/tests/functional/typed-sql/postgres-scalars-nullable/test.ts
  packages/client/tests/functional/typed-sql/postgres-scalars/test.ts
  packages/client/tests/functional/typed-sql/sqlite-scalars-nullable/test.ts
  packages/client/tests/functional/typed-sql/sqlite-scalars/test.ts
  sandbox/d1/src/index.ts
Labels: size:L

#25734 fix: Specify 'type': 'commonjs' in generated client package.json
  packages/client/src/generation/generateClient.ts
Labels: size:XS, lgtm

#25745 fix: update tests to account for a sqlserver fix in prisma/prisma-engines#5056
  package.json
  packages/client/package.json
  packages/client/tests/functional/batch-transaction-isolation-level/tests.ts
  packages/client/tests/functional/extensions/model.ts
  packages/client/tests/functional/extensions/query.ts
  packages/client/tests/functional/issues/18276-batch-order/tests.ts
  packages/client/tests/functional/logging/tests.ts
  packages/client/tests/functional/tracing/tests.ts
  packages/engines/package.json
  packages/fetch-engine/package.json
  packages/internals/package.json
  packages/migrate/package.json
  packages/schema-files-loader/package.json
  pnpm-lock.yaml
Labels: size:L

#25740 feat(client): generate unused `enum` definitions
  packages/client/src/generation/TSClient/TSClient.ts
  packages/client/src/generation/dmmf.ts
  packages/client/tests/e2e/enum-import-unused/_steps.ts
  packages/client/tests/e2e/enum-import-unused/package.json
  packages/client/tests/e2e/enum-import-unused/pnpm-lock.yaml
  packages/client/tests/e2e/enum-import-unused/prisma/schema.prisma
  packages/client/tests/e2e/enum-import-unused/readme.md
  packages/client/tests/e2e/enum-import-unused/tests/index.ts
  packages/client/tests/e2e/enum-import-unused/tsconfig.json
  packages/generator-helper/src/dmmf.ts
Labels: size:L, lgtm
