Repository prisma/prisma, pull requests merged in 2024-12, with the labels that each got.

#25767 fix(client): evert `"type": "commonjs"` addition in generated `package.json`
  packages/client/src/generation/generateClient.ts
Labels: size:XS

#25336 test(client): regression test for #19137
  packages/client/tests/functional/interactive-transactions/tests.ts
Labels: size:S

#25515 fix(adapter-neon): fix type parsing for PrismaNeonHTTP adapter
  packages/adapter-neon/package.json
  packages/adapter-neon/src/neon.ts
  packages/bundle-size/package.json
  packages/bundled-js-drivers/package.json
  packages/client/package.json
  pnpm-lock.yaml
Labels: size:S, lgtm

#25610 chore: switch to pnpm 9
  .devcontainer/Dockerfile
  .github/renovate.json
  .github/workflows/benchmark.yml
  .github/workflows/bundle-size.yml
  .github/workflows/release-ci.yml
  .github/workflows/release-latest.yml
  .github/workflows/scripts/setup.sh
  .github/workflows/test-template.yml
  CONTRIBUTING.md
  package.json
  packages/cli/src/__tests__/commands/__snapshots__/Version.test.ts.snap
  pnpm-lock.yaml
Labels: size:M

#25776 feat(client): expose internal tooling
  packages/client/src/runtime/index.ts
Labels: size:XS

#25871 feat: sqlite JSON support
  packages/adapter-d1/src/conversion.ts
  packages/adapter-libsql/src/conversion.ts
  packages/client/tests/functional/0-legacy-ports/json/_matrix.ts
  packages/client/tests/functional/0-legacy-ports/json/tests.ts
  packages/client/tests/functional/field-reference/json/__snapshots__/tests.ts.snap
  packages/client/tests/functional/field-reference/json/_matrix.ts
  packages/client/tests/functional/field-reference/json/tests.ts
  packages/client/tests/functional/issues/18854-extensions-db-null/_matrix.ts
  packages/client/tests/functional/issues/18854-extensions-db-null/tests.ts
  packages/client/tests/functional/issues/21454-$type-in-json/_matrix.ts
  packages/client/tests/functional/issues/21454-$type-in-json/tests.ts
  packages/client/tests/functional/json-fields/_matrix.ts
  packages/client/tests/functional/json-fields/tests.ts
  packages/client/tests/functional/json-null-types/_matrix.ts
  packages/client/tests/functional/json-null-types/tests.ts
  packages/client/tests/functional/raw-queries/typed-results/tests.ts
  packages/client/tests/functional/typed-sql/sqlite-scalars-nullable/prisma/_schema.ts
  packages/client/tests/functional/typed-sql/sqlite-scalars-nullable/prisma/sql/findJson.sql
  packages/client/tests/functional/typed-sql/sqlite-scalars-nullable/prisma/sql/getJson.sql
  packages/client/tests/functional/typed-sql/sqlite-scalars-nullable/test.ts
  packages/client/tests/functional/typed-sql/sqlite-scalars/prisma/_schema.ts
  packages/client/tests/functional/typed-sql/sqlite-scalars/prisma/sql/findJson.sql
  packages/client/tests/functional/typed-sql/sqlite-scalars/prisma/sql/getJson.sql
  packages/client/tests/functional/typed-sql/sqlite-scalars/test.ts
Labels: lgtm

#25900 fix(client): make nested omit types work
  packages/client/src/runtime/core/types/exported/Result.ts
  packages/client/tests/functional/24835-omit-error/_matrix.ts
  packages/client/tests/functional/24835-omit-error/prisma/_schema.ts
  packages/client/tests/functional/24835-omit-error/test.ts
Labels: lgtm

#25914 fix(client): allow "passing" across rpc boundary in cloudflare workers
  packages/client/src/runtime/core/compositeProxy/createCompositeProxy.ts
  packages/client/src/runtime/core/model/utils/defaultProxyHandlers.ts
  packages/client/tests/functional/proxy-prototype/_matrix.ts
  packages/client/tests/functional/proxy-prototype/prisma/_schema.ts
  packages/client/tests/functional/proxy-prototype/test.ts
Labels: lgtm
