Repository prisma/prisma, pull requests merged in 2025-03, with the labels that each got.

#21370 fix: @prisma/nextjs-monorepo-workaround-plugin creates "schema.prisma1 could not be found" bug
  packages/nextjs-monorepo-workaround-plugin/index.js
Labels: PR: Bug

#26472 test(migrate): Regression test for the introspection of enum array column types
  packages/migrate/src/__tests__/MigrateDev.test.ts
  packages/migrate/src/__tests__/fixtures/enum-array-type-introspection/prisma/schema.prisma
Labels: kind/regression, topic: tests, lgtm

#26510 feat(cli): use ES2022
  packages/client/src/runtime/core/engines/accelerate/AccelerateEngine.ts
  tsconfig.build.regular.json
Labels: lgtm

#26511 fix(cli): init url showing unnecessary step
  packages/cli/src/Init.ts
  packages/cli/src/__tests__/commands/__snapshots__/Init.test.ts.snap
Labels: lgtm

#26483 feat(cli): define `prisma.config.ts` without requiring `@prisma/config`
  .prettierignore
  eslint.config.cjs
  packages/cli/.gitignore
  packages/cli/helpers/build.ts
  packages/cli/package.json
  packages/cli/src/config.ts
  packages/cli/src/types.ts
  packages/client/tests/e2e/prisma-config/_steps.ts
  packages/client/tests/e2e/prisma-config/pnpm-lock.yaml
  packages/client/tests/e2e/prisma-config/src/define-config-with-@prisma-config.ts
  packages/client/tests/e2e/prisma-config/src/define-config-with-prisma-config.ts
  packages/client/tests/e2e/prisma-config/src/export-config-with-@prisma-config.ts
  packages/client/tests/e2e/prisma-config/src/export-config-with-prisma-config.ts
  packages/client/tests/e2e/prisma-config/src/export-config-with-prisma.ts
  pnpm-lock.yaml
  sandbox/basic-sqlite-config/package.json
  sandbox/basic-sqlite-config/prisma.config.ts
Labels: lgtm

#26503 chore(client): optimise e2e tests Dockerfile image
  packages/client/tests/e2e/_utils/standard.dockerfile
Labels: lgtm

#26470 fix: ORM-671 fix client extension + omit api compile performance issue
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema-mongo/__snapshots__/binary.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema-mongo/__snapshots__/library.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema/__snapshots__/binary.test.ts.snap
  packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema/__snapshots__/library.test.ts.snap
  packages/client/src/generation/TSClient/Model.ts
  packages/client/src/generation/TSClient/PrismaClient.ts
  packages/client/src/runtime/core/types/exported/Extensions.ts
  packages/client/src/runtime/core/types/exported/Result.ts
Labels: automerge, lgtm

#26526 fix: dynamic libsql import with fallback
  packages/adapter-libsql/src/libsql.ts
Labels: lgtm

#20113 feat(instrumentation): add ability to filter span by `PrismaLayerType`
  packages/client/tests/functional/tracing-disabled/tests.ts
  packages/client/tests/functional/tracing-filtered-spans/_matrix.ts
  packages/client/tests/functional/tracing-filtered-spans/prisma/_schema.ts
  packages/client/tests/functional/tracing-filtered-spans/tests.ts
  packages/client/tests/functional/tracing-no-sampling/tests.ts
  packages/client/tests/functional/tracing/tests.ts
  packages/instrumentation/README.md
  packages/instrumentation/src/ActiveTracingHelper.ts
  packages/instrumentation/src/PrismaInstrumentation.ts
  sandbox/tracing/otelSetup.ts
Labels: topic: tracing, lgtm

#26624 refactor: drop legacy seed migration script warnings
  packages/migrate/src/__tests__/DbSeed.test.ts
  packages/migrate/src/commands/DbSeed.ts
  packages/migrate/src/commands/MigrateDev.ts
  packages/migrate/src/commands/MigrateReset.ts
  packages/migrate/src/utils/seed.ts
Labels: lgtm

#26579 fix(driver-adapters): Partially removed error capturing
  packages/client-engine-runtime/src/interpreter/QueryInterpreter.ts
  packages/client-engine-runtime/src/transactionManager/TransactionManager.test.ts
  packages/client-engine-runtime/src/transactionManager/TransactionManager.ts
  packages/client/src/runtime/core/engines/client/ClientEngine.ts
Labels: topic: error handling

#26698 fix(cli): don't use `readConfigFile` from `typescript` package
  packages/cli/package.json
  packages/cli/src/init/client-output-path.ts
  pnpm-lock.yaml
Labels: automerge

#26705 fix(migrate tests): improve test reliability by streamlining env vars and cwd reset between tests
  packages/migrate/jest.config.js
  packages/migrate/src/__tests__/Baseline.test.ts
  packages/migrate/src/__tests__/DbExecute.test.ts
  packages/migrate/src/__tests__/DbPull/cockroachdb.test.ts
  packages/migrate/src/__tests__/DbPull/mongodb.test.ts
  packages/migrate/src/__tests__/DbPull/mysql.test.ts
  packages/migrate/src/__tests__/DbPull/postgresql-extensions.test.ts
  packages/migrate/src/__tests__/DbPull/postgresql-missing-database.test.ts
  packages/migrate/src/__tests__/DbPull/postgresql-multischema.test.ts
  packages/migrate/src/__tests__/DbPull/postgresql-views.test.ts
  packages/migrate/src/__tests__/DbPull/postgresql.test.ts
  packages/migrate/src/__tests__/DbPull/schema-folder.test.ts
  packages/migrate/src/__tests__/DbPull/sqlite.test.ts
  packages/migrate/src/__tests__/DbPull/sqlserver.test.ts
  packages/migrate/src/__tests__/DbPush.test.ts
  packages/migrate/src/__tests__/MigrateDeploy.test.ts
  packages/migrate/src/__tests__/MigrateDev.test.ts
  packages/migrate/src/__tests__/MigrateDiff.test.ts
  packages/migrate/src/__tests__/MigrateReset.test.ts
  packages/migrate/src/__tests__/setup.ts
Labels: lgtm

#26601 feat(qc): Refactor dynamic placeholder approach
  packages/client-engine-runtime/src/QueryPlan.ts
  packages/client-engine-runtime/src/interpreter/renderQuery.test.ts
  packages/client-engine-runtime/src/interpreter/renderQuery.ts
  packages/client-engine-runtime/src/interpreter/renderQueryTemplate.test.ts
  packages/client-engine-runtime/src/interpreter/renderQueryTemplate.ts
Labels: PR: Feature

#26720 feat(qc): Transactional graphs
  packages/client-engine-runtime/src/QueryPlan.ts
  packages/client-engine-runtime/src/index.ts
  packages/client-engine-runtime/src/interpreter/QueryInterpreter.ts
  packages/client-engine-runtime/src/transactionManager/Transaction.ts
  packages/client-engine-runtime/src/transactionManager/TransactionManager.test.ts
  packages/client-engine-runtime/src/transactionManager/TransactionManager.ts
  packages/client/src/runtime/core/engines/client/ClientEngine.ts
  packages/client/tests/functional/issues/9678/tests.ts
Labels: PR: Feature

#26718 chore: add utm params to social CTAs
  README.md
Labels: lgtm

#26751 ci: add GitHub Action to Auto Close Stale GitHub Discussions
  .github/workflows/auto-close-github-discussions.yml
  .github/workflows/scripts/auto-close-github-discussions.js
  package.json
  pnpm-lock.yaml
Labels: lgtm
