Repository prisma/prisma, pull requests merged in 2025-04, with the labels that each got.

#26788 ci: Fixes failing Auto Close GH Discussions Action
  .github/workflows/auto-close-github-discussions.yml
Labels: lgtm

#26812 fix(client): resolve type error in tests using dev builds
  packages/client/src/runtime/index.ts
Labels: automerge

#26825 ci: updates label names to match GH Discussion qualifying for closure
  .github/workflows/scripts/auto-close-github-discussions.js
Labels: lgtm

#26700 feat(cli): add MCP server
  packages/cli/package.json
  packages/cli/src/CLI.ts
  packages/cli/src/Init.ts
  packages/cli/src/MCP.ts
  packages/cli/src/bin.ts
  pnpm-lock.yaml
Labels: automerge, lgtm

#26845 docs(README): add note about MCP server
  README.md
Labels: lgtm

#26727 feat: ORM-596 file splitting in ESM generator
  packages/client-generator-ts/src/TSClient/Args.ts
  packages/client-generator-ts/src/TSClient/Count.ts
  packages/client-generator-ts/src/TSClient/Datasources.ts
  packages/client-generator-ts/src/TSClient/Enum.ts
  packages/client-generator-ts/src/TSClient/FieldRefInput.ts
  packages/client-generator-ts/src/TSClient/Generable.ts
  packages/client-generator-ts/src/TSClient/GenerateContext.ts
  packages/client-generator-ts/src/TSClient/Input.ts
  packages/client-generator-ts/src/TSClient/Model.ts
  packages/client-generator-ts/src/TSClient/ModelFieldRefs.ts
  packages/client-generator-ts/src/TSClient/Output.ts
  packages/client-generator-ts/src/TSClient/PrismaClient.ts
  packages/client-generator-ts/src/TSClient/SelectIncludeOmit.ts
  packages/client-generator-ts/src/TSClient/TSClient.ts
  packages/client-generator-ts/src/TSClient/TypeMap.ts
  packages/client-generator-ts/src/TSClient/common.ts
  packages/client-generator-ts/src/TSClient/file-generators/ClassFile.ts
  packages/client-generator-ts/src/TSClient/file-generators/ClientFile.ts
  packages/client-generator-ts/src/TSClient/file-generators/CommonInputTypesFile.ts
  packages/client-generator-ts/src/TSClient/file-generators/EnumsFile.ts
  packages/client-generator-ts/src/TSClient/file-generators/ModelFile.ts
  packages/client-generator-ts/src/TSClient/file-generators/ModelsFile.ts
  packages/client-generator-ts/src/TSClient/file-generators/PrismaNamespaceFile.ts
  packages/client-generator-ts/src/TSClient/globalOmit.ts
  packages/client-generator-ts/src/TSClient/index.ts
  packages/client-generator-ts/src/TSClient/utils/type-builders.ts
  packages/client-generator-ts/src/generateClient.ts
  packages/client-generator-ts/src/utils.ts
  packages/client-generator-ts/src/utils/buildNFTAnnotations.test.ts
  packages/client-generator-ts/src/utils/buildNFTAnnotations.ts
  packages/client-generator-ts/src/utils/common.ts
  packages/ts-builders/src/Import.ts
  sandbox/basic-sqlite/.gitignore
  sandbox/basic-sqlite/index.ts
  sandbox/basic-sqlite/prisma/schema.prisma
Labels: lgtm

#26898 feat: properly implement m2m connect
  packages/client-engine-runtime/src/QueryPlan.ts
  packages/client-engine-runtime/src/interpreter/generators.test.ts
  packages/client-engine-runtime/src/interpreter/generators.ts
  packages/client-engine-runtime/src/interpreter/renderQuery.test.ts
  packages/client-engine-runtime/src/interpreter/renderQuery.ts
Labels: lgtm

#26906 fix: fix join on missing UNIQUE
  packages/client-engine-runtime/src/interpreter/QueryInterpreter.ts
Labels: lgtm

#26918 build(instrumentation): Emit ESM
  packages/instrumentation/helpers/build.ts
  packages/instrumentation/package.json
  packages/instrumentation/src/constants.ts
Labels: lgtm

#26951 fix(ci): Fix `wasm-bindgen` installation error on CI
  .github/workflows/build-engine-branch.yml
Labels: lgtm

#26929 feat(qc): Data mapper
  packages/client-engine-runtime/src/QueryPlan.ts
  packages/client-engine-runtime/src/interpreter/DataMapper.ts
  packages/client-engine-runtime/src/interpreter/QueryInterpreter.ts
  packages/client/tests/functional/client-engine-known-failures-js_libsql.txt
  packages/client/tests/functional/client-engine-known-failures-js_pg.txt
Labels: lgtm

#26959 fix: wasmBasePath for query engine builds
  packages/client-generator-ts/src/utils/buildGetWasmModule.ts
Labels: lgtm

#26950 fix(d1): ORM-885 remove miniflare from D1 adapter
  packages/adapter-d1/package.json
  packages/adapter-d1/src/d1.ts
  pnpm-lock.yaml
Labels: lgtm

#26984 feat(generator): allow overwriting old client generator output with new client generator output
  packages/client-generator-ts/src/generateClient.ts
Labels: lgtm
