Repository prisma/prisma, pull requests merged in 2025-02, with the labels that each got.

#26229 chore: prisma postgres init copy changes
  packages/cli/package.json
  packages/cli/src/Init.ts
  packages/cli/src/__tests__/commands/__snapshots__/Init.test.ts.snap
  packages/cli/src/platform/_lib/utils.ts
  pnpm-lock.yaml
Labels: lgtm

#26225 chore: rename Env to Scope and error kinds to align with provider
  packages/adapter-d1/src/d1.ts
  packages/adapter-libsql/src/libsql.ts
  packages/adapter-neon/src/neon.ts
  packages/adapter-pg-worker/src/pg.ts
  packages/adapter-pg/src/pg.ts
  packages/adapter-planetscale/src/planetscale.ts
  packages/client/src/runtime/core/engines/client/ClientEngine.ts
  packages/client/src/runtime/core/engines/client/interpreter/QueryInterpreter.ts
  packages/client/src/runtime/core/engines/client/interpreter/renderQuery.ts
  packages/client/src/runtime/core/engines/client/interpreter/renderQueryTemplate.ts
  packages/client/src/runtime/core/engines/client/interpreter/scope.ts
  packages/client/src/runtime/core/engines/client/types/QueryCompiler.ts
  packages/driver-adapter-utils/src/types.ts
Labels: lgtm

#26258 fix(client): #1428
  packages/client/src/runtime/core/init/getEngineInstance.ts
Labels: lgtm

#14045 docs(README): improve comments about using await
  README.md
Labels: PR: Docs

#21577 fix(client): normalize outputDir
  packages/client/src/generation/generateClient.ts
Labels: PR: Bug, lgtm

#26345 chore(root): ORM-646: Update CONTRIBUTING.md with no Windows policy
  .github/actions/setup/action.yml
  .github/workflows/benchmark.yml
  .github/workflows/bundle-size.yml
  .github/workflows/release-ci.yml
  .github/workflows/release-latest.yml
  .github/workflows/test-template.yml
  CONTRIBUTING.md
  package.json
  sandbox/basic-sqlite/package.json
  sandbox/driver-adapters/package.json
Labels: lgtm

#26372 fix: do not show NPS survey when --no-hints is provided
  packages/cli/src/Generate.ts
  packages/cli/src/__tests__/commands/Generate.test.ts
Labels: lgtm

#26378 feat(migrate): Not offering a database reset
  packages/internals/src/utils/canPrompt.ts
  packages/migrate/src/__tests__/Baseline.test.ts
  packages/migrate/src/__tests__/DbPush.test.ts
  packages/migrate/src/__tests__/MigrateDev.test.ts
  packages/migrate/src/commands/DbPush.ts
  packages/migrate/src/commands/MigrateDev.ts
Labels: kind/feature, topic: migrate

#26399 ci: remove packages pattern from dependabot
  .github/dependabot.yml
Labels: lgtm

#26383 feat(config): hide third-party dependencies from type exports, fix e2e test
  packages/cli/src/utils/loadConfig.ts
  packages/client/tests/e2e/prisma-config/pnpm-lock.yaml
  packages/config/helpers/build.ts
  packages/config/src/PrismaConfig.ts
  packages/config/src/__tests__/defineConfig.test.ts
  packages/config/src/__tests__/loadConfigFromFile.test.ts
  packages/config/src/defaultConfig.ts
  packages/config/src/defaultTestConfig.ts
  packages/config/src/defineConfig.ts
  packages/config/src/index.ts
  packages/config/src/loadConfigFromFile.ts
  packages/config/src/utils.ts
  packages/migrate/src/bin.ts
  sandbox/basic-sqlite-config/.gitignore
  sandbox/basic-sqlite-config/custom/prisma/schema.prisma
  sandbox/basic-sqlite-config/index.ts
  sandbox/basic-sqlite-config/package.json
  sandbox/basic-sqlite-config/prisma.config.ts
  sandbox/basic-sqlite-config/tsconfig.json
Labels: lgtm

#26315 fix(config loading): ORM-607 review follow ups
  packages/cli/src/utils/loadConfig.test.ts
  packages/internals/src/utils/loadEnvFile.ts
Labels: lgtm

#26421 feat(client): replace "detect-runtime" with internal implementation
  packages/client/package.json
  packages/client/src/runtime/utils/getRuntime.ts
  pnpm-lock.yaml
Labels: lgtm

#26461 chore: Update issue and feature request templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: lgtm
